name: ISS Map Auto-Updater

permissions:
  contents: write

on:
  push:
    branches: [ main ]
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

jobs:
  update-iss-map:
    runs-on: ubuntu-latest

    steps:
    - name: "Checkout repo"
      uses: actions/checkout@v4

    - name: "Set up Python"
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: "Install dependencies"
      run: pip install plotly requests pandas

    - name: "Randomized delay (0–50 min)"
      run: |
        DELAY=$((RANDOM % 3000))
        echo "Sleeping for $DELAY seconds (~$((DELAY/60)) minutes)"
        sleep $DELAY

    - name: "Gatekeeper"
      id: gate
      run: python .github/workflows/gatekeeper.py

    - name: "Run mapbuilder (updates CSV + HTML)"
      if: ${{ steps.gate.outputs.run == 'true' }}
      run: python mapbuilder.py

    - name: "Commit & push changes"
      if: ${{ steps.gate.outputs.run == 'true' }}
      run: |
        git config user.name "dzweben"
        git config user.email "danny.zweben99@gmail.com"
        git add iss_map.html iss_positions.csv
        git commit -m "auto: Update ISS map $(date -u +'%Y-%m-%d %H:%M:%S UTC')" || echo "No changes to commit"
        git push
