name: ISS Map Auto-Updater

permissions:
  contents: write

on:
  schedule:
    # Run every hour (UTC)
    - cron: "0 * * * *"
  workflow_dispatch: {}

jobs:
  update-iss-map:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
      with:
        persist-credentials: true

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Install dependencies
      run: pip install plotly requests pandas

    - name: Randomized delay (0–50 min)
      run: sleep $((RANDOM % 3000))

    - name: Gate: decide whether to run (aim 5–20 commits/day)
      id: gate
      run: |
        python - <<'PY'
        import os, random
        from datetime import datetime, timezone
        import pandas as pd

        now = datetime.now(timezone.utc)
        today = now.strftime('%Y-%m-%d')

        # Deterministic daily target between 5 and 20
        random.seed(today)
        target = random.randint(5, 20)

        # Count how many points already logged today
        count = 0
        try:
            df = pd.read_csv('iss_positions.csv')
            if 'ts' in df.columns:
                count = sum(str(ts).startswith(today) for ts in df['ts'])
        except Exception:
            pass

        remaining_hours = 24 - now.hour

        if count >= target:
            decision = False
            reason = f"already reached target {target} (count={count})"
        else:
            remaining_needed = max(0, target - count)
            # Probability increases as the day runs out
            p = min(1.0, max(0.15, remaining_needed / max(1, remaining_hours)))
            decision = random.random() < p
            reason = f"count={count}, target={target}, remaining_hours={remaining_hours}, p={p:.2f}"

        print(f"Decision={decision} ({reason})")
        with open(os.environ['GITHUB_OUTPUT'], 'a') as fh:
            fh.write(f"run={'true' if decision else 'false'}\n")
        PY

    - name: Run mapbuilder (updates CSV + HTML)
      if: steps.gate.outputs.run == 'true'
      run: python mapbuilder.py

    - name: Commit & push changes
      if: steps.gate.outputs.run == 'true'
      run: |
        git config user.name "dzweben"
        git config user.email "danny.zweben99@gmail.com"
        git add iss_map.html iss_positions.csv
        git commit -m "auto: update ISS map $(date -u +'%Y-%m-%d %H:%M:%S UTC')" || echo "No changes to commit"
        git push
