name: ISS Map Auto-Updater

permissions:
  contents: write

on:
  schedule:
    - cron: "0 * * * *"   # every hour UTC
  workflow_dispatch: {}

jobs:
  update-iss-map:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Install dependencies
      run: pip install plotly requests pandas

    - name: Randomized delay (0–50 min)
      run: sleep $((RANDOM % 3000))

    - name: Gate: decide whether to run (aim 5–20 commits/day)
      id: gate
      run: |
        today=$(date -u +%Y-%m-%d)
        count=$(grep -c "^$today" iss_positions.csv 2>/dev/null || echo 0)
        # deterministic daily target between 5 and 20
        target=$(( ( $(date -d $today +%s) % 16 ) + 5 ))
        remaining_hours=$((24 - $(date -u +%H)))

        if [ "$count" -ge "$target" ]; then
          decision=false
        else
          remaining_needed=$((target - count))
          # ensure probability increases as day goes on
          prob=$(echo "scale=2; $remaining_needed / $remaining_hours" | bc -l)
          [ $(echo "$prob < 0.15" | bc -l) -eq 1 ] && prob=0.15
          roll=$(awk -v seed=$(date +%s%N) 'BEGIN{srand(seed); print rand()}')
          decision=$(awk -v r=$roll -v p=$prob 'BEGIN{print (r<p)?"true":"false"}')
        fi

        echo "run=$decision" >> $GITHUB_OUTPUT

    - name: Run mapbuilder (updates CSV + HTML)
      if: steps.gate.outputs.run == 'true'
      run: python mapbuilder.py

    - name: Commit & push changes
      if: steps.gate.outputs.run == 'true'
      run: |
        git config user.name "dzweben"
        git config user.email "danny.zweben99@gmail.com"
        git add iss_map.html iss_positions.csv
        git commit -m "auto: update ISS map $(date -u +'%Y-%m-%d %H:%M:%S UTC')" || echo "No changes to commit"
        git push
